version: '3.8'

services:

  eurekaserver:
    build:
      context: ./eurekaserver
    ports:
      - "8761:8761"
    networks:
      - petverse-net

  configserver:
    build:
      context: ./configserver
    ports:
      - "8888:8888"
    depends_on:
      - eurekaserver
    networks:
      - petverse-net

  activityservice:
    build:
      context: ./activityservice
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - petverse-net

  apigateway:
    build:
      context: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - petverse-net

  userservice:
    build:
      context: ./userservice
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - postgres
    networks:
      - petverse-net

  petservice:
    build:
      context: ./petservice
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - postgres
    networks:
      - petverse-net

  notificationservice:
    build:
      context: ./notificationservice
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - petverse-net


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: petcaredb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - petverse-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - petverse-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus # Prometheus’un veritabanını kalıcı hale getirir.
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - petverse-net  
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - petverse-net
    volumes:
    - grafana-storage:/var/lib/grafana  
      
networks:
  petverse-net:
    driver: bridge

volumes:
  pgdata:
  grafana-storage:
  prometheus_data:
