version: '3.8'

services:

  eurekaserver:
    build:
      context: ./eurekaserver
    ports:
      - "8761:8761"
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/eurekaserver:/app/logs

  configserver:
    build:
      context: ./configserver
    ports:
      - "8888:8888"
    depends_on:
      - eurekaserver
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/configserver:/app/logs

  activityservice:
    build:
      context: ./activityservice
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/activityservice:/app/logs

  apigateway:
    build:
      context: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - configserver
      - eurekaserver
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/apigateway:/app/logs

  userservice:
    build:
      context: ./userservice
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - postgres
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/userservice:/app/logs

  petservice:
    build:
      context: ./petservice
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - postgres
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/petservice:/app/logs

  notificationservice:
    build:
      context: ./notificationservice
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - TZ=Europe/Istanbul
    networks:
      - petverse-net
    volumes:
      - ./logs/notificationservice:/app/logs

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: petcaredb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - petverse-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - petverse-net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Bellek sınırı burada
    ports:
      - "9200:9200"


  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/app/logs

    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
networks:
  petverse-net:
    driver: bridge

volumes:
  pgdata:
