server:
  port: 8084

spring:
  application:
    name: activityservice
  datasource:
    url: jdbc:postgresql://postgres:5432/petcaredb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: activityservice

springdoc:
  api-docs:
    path: /activity/v3/api-docs
  swagger-ui:
    path: /activity/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      petService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        failureRateThreshold: 100
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.lang.Exception
          - java.lang.RuntimeException
          - feign.FeignException
          - feign.FeignException$ServiceUnavailable
          - org.springframework.web.server.ResponseStatusException

