server:
  port: 8080

spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://configserver:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: petservice
          uri: lb://petservice
          predicates:
            - Path=/api/pets/**
          filters:
            - StripPrefix=1

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
      