server:
  port: 8080

spring:
  application:
    name: apigateway

  config:
    import: optional:configserver:http://configserver:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: petservice
          uri: lb://petservice
          predicates:
            - Path=/petservice/**
          filters:
            - StripPrefix=1

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
      