server:
  port: 8080

spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://configserver:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: petservice
          uri: lb://petservice
          predicates:
            - Path=/api/pets/**
          filters:
            - StripPrefix=1

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: activityservice
          uri: lb://activityservice
          predicates:
            - Path=/api/activities/**
          filters:
            - StripPrefix=1

  
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: activity-service
        url: http://localhost:8084/activity/v3/api-docs
      - name: notification-service
        url: http://localhost:8085/notification/v3/api-docs
      - name: pet-service
        url: http://localhost:8083/pet/v3/api-docs      
      - name: user-service
        url: http://localhost:8082/v3/api-docs
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
