server:
  port: 8082

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://postgres:5432/petcaredb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka

jwt:
  issuer: userservice
  ttl: 15m
  public-key: classpath:jwt/app.pub
  private-key: classpath:jwt/app.key
