server:
  port: 8083

spring:
  application:
    name: petservice
  datasource:
    url: jdbc:postgresql://postgres:5432/petcaredb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: a7574412-5e24-4900-bb22-f2f88f47b78f

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    prefer-ip-address: true
